/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CanvasList: typeof import('./../src/components/tools/canvas-list/CanvasList.vue')['default']
    copy: typeof import('./../src/components/widgets/w-image/WImage copy.vue')['default']
    HelloWorld: typeof import('./../src/components/HelloWorld.vue')['default']
    ImagePanel: typeof import('./../src/components/panels/image-panel/ImagePanel.vue')['default']
    Moveable: typeof import('./../src/components/tools/moveable/Moveable.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NButtonGroup: typeof import('naive-ui')['NButtonGroup']
    NCard: typeof import('naive-ui')['NCard']
    NCollapse: typeof import('naive-ui')['NCollapse']
    NCollapseItem: typeof import('naive-ui')['NCollapseItem']
    NDivider: typeof import('naive-ui')['NDivider']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NFlex: typeof import('naive-ui')['NFlex']
    NForm: typeof import('naive-ui')['NForm']
    NFormItemRow: typeof import('naive-ui')['NFormItemRow']
    NH2: typeof import('naive-ui')['NH2']
    NIcon: typeof import('naive-ui')['NIcon']
    NImage: typeof import('naive-ui')['NImage']
    NInfiniteScroll: typeof import('naive-ui')['NInfiniteScroll']
    NInput: typeof import('naive-ui')['NInput']
    NInputNumber: typeof import('naive-ui')['NInputNumber']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NLayoutFooter: typeof import('naive-ui')['NLayoutFooter']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NPopover: typeof import('naive-ui')['NPopover']
    NScrollbar: typeof import('naive-ui')['NScrollbar']
    NSkeleton: typeof import('naive-ui')['NSkeleton']
    NSpace: typeof import('naive-ui')['NSpace']
    NSpin: typeof import('naive-ui')['NSpin']
    NTab: typeof import('naive-ui')['NTab']
    NTabPane: typeof import('naive-ui')['NTabPane']
    NTabs: typeof import('naive-ui')['NTabs']
    NTag: typeof import('naive-ui')['NTag']
    NText: typeof import('naive-ui')['NText']
    ResizeTool: typeof import('./../src/components/tools/resize-tool/ResizeTool.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UseElementSize: typeof import('@vueuse/components')['UseElementSize']
    WaterFall: typeof import('./../src/components/layouts/water-fall/WaterFall.vue')['default']
    WidgetDrag: typeof import('./../src/components/tools/widget-drag/WidgetDrag.vue')['default']
    WidgetRenderer: typeof import('./../src/components/layouts/widget-renderer/WidgetRenderer.vue')['default']
    WImage: typeof import('./../src/components/widgets/w-image/WImage.vue')['default']
    WImageSetting: typeof import('./../src/components/widgets/w-image/WImageSetting.vue')['default']
    WPage: typeof import('./../src/components/widgets/w-page/WPage.vue')['default']
    WPageSetting: typeof import('./../src/components/widgets/w-page/WPageSetting.vue')['default']
  }
}
